#!/usr/bin/env python3
"""
SEO Audit Report — tangison.com
Generated by Z.ai
"""

import os, sys, hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak, HRFlowable
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ─── Font Registration ───────────────────────────────────────
pdfmetrics.registerFont(TTFont('Carlito', '/usr/share/fonts/truetype/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Carlito-Bold', '/usr/share/fonts/truetype/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSerif', '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSerif-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'))
registerFontFamily('Carlito', normal='Carlito', bold='Carlito-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('DejaVuSerif', normal='DejaVuSerif', bold='DejaVuSerif-Bold')

# ─── Palette ─────────────────────────────────────────────────
ACCENT       = colors.HexColor('#2390b4')
TEXT_PRIMARY  = colors.HexColor('#201f1d')
TEXT_MUTED    = colors.HexColor('#89867d')
BG_SURFACE   = colors.HexColor('#e8e6e0')
BG_PAGE      = colors.HexColor('#f4f3f1')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# Severity colors
CRITICAL_COLOR = colors.HexColor('#c0392b')
HIGH_COLOR     = colors.HexColor('#d35400')
MEDIUM_COLOR   = colors.HexColor('#f39c12')
LOW_COLOR      = colors.HexColor('#27ae60')

# ─── Page Setup ──────────────────────────────────────────────
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ─── Styles ──────────────────────────────────────────────────
body_style = ParagraphStyle(
    name='Body', fontName='DejaVuSerif', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, spaceAfter=8,
    textColor=TEXT_PRIMARY
)
h1_style = ParagraphStyle(
    name='H1', fontName='DejaVuSerif', fontSize=20,
    leading=26, alignment=TA_LEFT, spaceBefore=18, spaceAfter=10,
    textColor=TEXT_PRIMARY
)
h2_style = ParagraphStyle(
    name='H2', fontName='DejaVuSerif', fontSize=15,
    leading=20, alignment=TA_LEFT, spaceBefore=14, spaceAfter=8,
    textColor=ACCENT
)
h3_style = ParagraphStyle(
    name='H3', fontName='DejaVuSerif', fontSize=12,
    leading=16, alignment=TA_LEFT, spaceBefore=10, spaceAfter=6,
    textColor=TEXT_PRIMARY
)
muted_style = ParagraphStyle(
    name='Muted', fontName='DejaVuSerif', fontSize=9.5,
    leading=14, alignment=TA_LEFT, spaceAfter=4,
    textColor=TEXT_MUTED
)
cell_style = ParagraphStyle(
    name='Cell', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    wordWrap='CJK'
)
cell_center = ParagraphStyle(
    name='CellCenter', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_CENTER, textColor=TEXT_PRIMARY
)
header_cell = ParagraphStyle(
    name='HeaderCell', fontName='DejaVuSerif', fontSize=10,
    leading=13, alignment=TA_CENTER, textColor=colors.white
)
bullet_style = ParagraphStyle(
    name='Bullet', fontName='DejaVuSerif', fontSize=10.5,
    leading=16, alignment=TA_LEFT, spaceAfter=4,
    textColor=TEXT_PRIMARY, leftIndent=20, bulletIndent=8
)
callout_style = ParagraphStyle(
    name='Callout', fontName='DejaVuSerif', fontSize=10.5,
    leading=17, alignment=TA_LEFT, spaceAfter=8,
    textColor=TEXT_PRIMARY, leftIndent=16, borderPadding=8,
    borderWidth=0, backColor=colors.HexColor('#f0f8fa')
)
severity_critical = ParagraphStyle(
    name='SevCritical', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_CENTER, textColor=colors.white
)
severity_high = ParagraphStyle(
    name='SevHigh', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_CENTER, textColor=colors.white
)
severity_medium = ParagraphStyle(
    name='SevMedium', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_CENTER, textColor=colors.white
)
severity_low = ParagraphStyle(
    name='SevLow', fontName='DejaVuSerif', fontSize=9.5,
    leading=13, alignment=TA_CENTER, textColor=colors.white
)

# ─── Helpers ─────────────────────────────────────────────────
def sev_cell(text, level):
    """Return a Paragraph styled by severity level."""
    styles_map = {
        'CRITICAL': (severity_critical, CRITICAL_COLOR),
        'HIGH': (severity_high, HIGH_COLOR),
        'MEDIUM': (severity_medium, MEDIUM_COLOR),
        'LOW': (severity_low, LOW_COLOR),
    }
    st, bg = styles_map.get(level, (cell_center, BG_SURFACE))
    return Paragraph(f'<b>{text}</b>', st), bg

def make_table(data_rows, col_widths=None, has_header=True):
    """Build a styled table with alternating rows."""
    t = Table(data_rows, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ]
    if has_header:
        style_cmds.append(('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR))
        style_cmds.append(('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT))
    # Alternating rows
    for i in range(1, len(data_rows)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    return t

def hr():
    return HRFlowable(width="100%", thickness=0.5, color=TEXT_MUTED, spaceAfter=10, spaceBefore=10)

# ─── Build Story ─────────────────────────────────────────────
story = []

# ============================================================
# SECTION 1: EXECUTIVE SUMMARY
# ============================================================
story.append(Paragraph('<b>Executive Summary</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The SEO audit of tangison.com reveals a site with solid architectural foundations but critical configuration errors that completely undermine its search visibility. The most damaging issue is that every canonical URL on the site points to <b>tangison-labs.vercel.app</b> instead of <b>tangison.com</b>, causing Google to associate all page authority with the Vercel deployment subdomain rather than the production domain. This misconfiguration is the primary reason the site has zero pages indexed by Google, as confirmed by a site:tangison.com search returning no results.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Beyond the canonical catastrophe, the site lacks any structured data (JSON-LD schema markup) across all 39 pages and 4 subdomains, eliminating the possibility of rich snippets in search results. Four service pages display duplicate brand names in their title tags ("AI Consulting | TANGISON | TANGISON"), and there is no www-to-non-www redirect, creating duplicate content signals. The subdomains sme-academy.tangison.com and feorm.tangison.com have no canonical tags, no Open Graph metadata, and no H1 headings, making them effectively invisible to search engines.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'On the positive side, the site has a well-structured URL hierarchy, uses Next.js Image optimization with AVIF/WebP formats, has descriptive alt text on nearly all images, and every page sets a canonical tag (even if the domain is wrong). The 301 redirect configuration for legacy URL paths is properly implemented, and security headers are comprehensive. Fixing the canonical URL domain will resolve the most critical layer and unlock the value of the existing on-page optimization work.',
    body_style
))

# Overall score box
story.append(Spacer(1, 12))
score_data = [
    [Paragraph('<b>Layer</b>', header_cell),
     Paragraph('<b>Weight</b>', header_cell),
     Paragraph('<b>Score (1-10)</b>', header_cell),
     Paragraph('<b>Top Issue</b>', header_cell)],
    [Paragraph('Technical Foundation', cell_style),
     Paragraph('25%', cell_center),
     Paragraph('3', cell_center),
     Paragraph('Canonical URLs point to vercel.app, not tangison.com', cell_style)],
    [Paragraph('On-Page Optimization', cell_style),
     Paragraph('20%', cell_center),
     Paragraph('5', cell_center),
     Paragraph('Zero structured data; duplicate brand in titles', cell_style)],
    [Paragraph('Content Quality', cell_style),
     Paragraph('25%', cell_center),
     Paragraph('6', cell_center),
     Paragraph('Thin homepage content; no E-E-A-T signals', cell_style)],
    [Paragraph('Link Profile', cell_style),
     Paragraph('15%', cell_center),
     Paragraph('2', cell_center),
     Paragraph('Zero external backlinks; no domain authority', cell_style)],
    [Paragraph('Competitive Position', cell_style),
     Paragraph('15%', cell_center),
     Paragraph('2', cell_center),
     Paragraph('Not indexed by Google; zero organic presence', cell_style)],
]
score_table = make_table(score_data, col_widths=[110, 60, 80, AVAILABLE_WIDTH - 250])
story.append(score_table)
story.append(Spacer(1, 6))
story.append(Paragraph('<b>Overall Health Score: 3.2 / 10</b> — Critical. Comprehensive overhaul required before any content or authority strategy can be effective.', callout_style))

# ============================================================
# SECTION 2: LAYER 1 — TECHNICAL FOUNDATION
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Layer 1: Technical Foundation</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>Crawlability</b>', h2_style))
story.append(Paragraph(
    'The robots.txt file at tangison.com/robots.txt is properly configured with a single Allow directive for all user agents and a correct Sitemap reference pointing to https://tangison.com/sitemap.xml. However, the file does not block crawling of technical paths such as /api/ and /_next/, which wastes crawl budget on non-indexable resources. The XML sitemap lists 40 URLs with appropriate priority values, though the article slugs are hardcoded rather than dynamically pulled from the data layer, creating a maintenance risk where new articles may not be added to the sitemap.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    'A significant sitemap issue is that all lastModified timestamps use new Date() at build time, meaning every URL gets the current date as its last modification timestamp on every deployment. This defeats the purpose of lastModified for search engines, as the timestamp changes on every build regardless of whether the content actually changed. Additionally, the /studio page route exists in the application but is missing from the sitemap.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Indexability — CRITICAL FAILURE</b>', h2_style))
story.append(Paragraph(
    'The most damaging finding in this entire audit is that <b>every canonical URL on the site points to tangison-labs.vercel.app instead of tangison.com</b>. The Next.js metadataBase in the root layout uses process.env.NEXT_PUBLIC_SITE_URL which apparently resolves to the Vercel deployment URL in production. This means Google sees every page as a duplicate of the vercel.app version and attributes all authority to that subdomain. A site:tangison.com search returns zero results, confirming the site has no Google index coverage whatsoever. Meanwhile, the vercel.app domain likely receives whatever crawl attention Google allocates.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    'Additionally, there is no 301 redirect from www.tangison.com to tangison.com (or vice versa). Both hostnames serve identical content with 200 status codes, creating a duplicate content signal. Similarly, trailing slash inconsistency exists: both /services/applied-ai and /services/applied-ai/ return 200 with identical content. While internal links consistently omit the trailing slash, the lack of a server-level redirect is a duplicate content risk.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Performance</b>', h2_style))
story.append(Paragraph(
    'The site is built on Next.js with static generation (SSG) for article pages and deploys on Vercel with global edge infrastructure, which provides strong baseline performance. The Next.js Image component is used throughout with AVIF and WebP format configuration in next.config.ts. Security headers are comprehensive and include HSTS, X-Frame-Options, Content-Security-Policy, and X-Content-Type-Options. The viewport meta tag is properly configured for mobile, and the site does not use maximum-scale=1, allowing users to pinch-zoom. HTTPS is enforced across the entire site with valid SSL certificates.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Rendering</b>', h2_style))
story.append(Paragraph(
    'As a Next.js application with static generation, critical page content is present in the initial HTML response, making it fully accessible to search engine crawlers. Dynamic article routes use generateStaticParams for build-time pre-rendering. No JavaScript-dependent critical content was identified. The server-side rendering approach ensures that all headings, text, and links are visible to crawlers without JavaScript execution.',
    body_style
))

# ============================================================
# SECTION 3: LAYER 2 — ON-PAGE OPTIMIZATION
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Layer 2: On-Page Optimization</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>Title Tags</b>', h2_style))
story.append(Paragraph(
    'Every page has a unique title tag, which is positive. However, four service and insight pages exhibit a duplicate brand name issue where the title renders as "Applied AI | TANGISON | TANGISON" instead of "Applied AI | TANGISON". This is likely caused by the Next.js title template combining with page-level titles that already include the brand suffix. The root layout defines a title template of "%s | TANGISON", so individual pages should not include "| TANGISON" in their own title strings. The home page title "TANGISON | Applied AI Laboratory" at 59 characters is within the recommended 50-60 character limit for SERP display. The About page uses an em dash ("About — Applied AI Lab in Namibia") while other pages use a pipe separator, creating a minor branding inconsistency.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Meta Descriptions</b>', h2_style))
story.append(Paragraph(
    'All 39 pages have unique meta descriptions, which is excellent. The homepage description at 155 characters falls within the recommended 150-160 character range and includes a clear value proposition and location signal ("Windhoek, Namibia"). However, most descriptions are purely descriptive and lack a compelling call to action. For example, the services page description reads "We build custom AI systems..." but does not invite the reader to take a specific next step. Adding action-oriented language like "Discover how..." or "Get started with..." would improve click-through rates from search results.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Heading Structure</b>', h2_style))
story.append(Paragraph(
    'Most pages maintain proper heading hierarchy with a single H1 containing the primary keyword, followed by logical H2 and H3 nesting. However, the /products page has no H1 tag at all, using only H2 headings for product names. This is a significant SEO gap because Google uses the H1 as a primary signal for page topic. Additionally, the article detail pages render the article title as an H1, but the heading image above it has an empty alt attribute (alt=""), which fails both accessibility and SEO standards for content images. The image should use the article title as its alt text.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>URL Structure</b>', h2_style))
story.append(Paragraph(
    'URLs are clean, descriptive, and use hyphens consistently. The service hierarchy follows a logical pattern (/services/applied-ai/custom-ai-systems), and product URLs are flat and readable (/products/skillscamp). Seven legacy redirect paths are properly configured with 301 status codes (/architecture to /services, /manifesto to /about, etc.). No excessive URL parameters or session IDs were found. The URL structure supports both human readability and search engine understanding.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Internal Linking</b>', h2_style))
story.append(Paragraph(
    'The navigation menu provides access to all major sections within two clicks from the homepage. The footer contains 6 columns of links covering services, products, company, insights, connect, and the Tangison Technologies group. Service sub-pages link to /contact as a CTA pattern. Articles cross-reference each other through internalLinks data. However, service parent pages (e.g., /services/applied-ai) do not link to their own sub-specialization pages, missing an opportunity to distribute authority deeper into the site hierarchy. The /products index page also lacks outbound links to its children from the main content area.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Image Optimization</b>', h2_style))
story.append(Paragraph(
    'The site uses the Next.js Image component exclusively with no raw img tags found. AVIF and WebP formats are configured in next.config.ts, and responsive srcset and sizes attributes are used on hero images. Nearly all images have descriptive alt text, with only one exception: the article heading image at /insights/articles/[slug] uses alt="". Image files are appropriately sized, and gallery images have both PNG and WebP versions available. This is a strong area of the site that requires only the single alt text fix.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Structured Data — COMPLETELY ABSENT</b>', h2_style))
story.append(Paragraph(
    'Zero JSON-LD structured data exists anywhere on the site. No Organization schema, no WebSite schema with SearchAction, no BreadcrumbList on any page, no Article schema on blog posts, no Product schema on product pages, no Service schema on service pages, and no LocalBusiness schema on the contact page. This is a major gap that prevents the site from earning any rich snippets in Google search results, including article bylines, breadcrumb trails, and product information panels. Implementing structured data across the site would provide an immediate and significant improvement in search visibility and click-through rates.',
    body_style
))

# ============================================================
# SECTION 4: LAYER 3 — CONTENT QUALITY
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Layer 3: Content Quality</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>E-E-A-T Assessment</b>', h2_style))
story.append(Paragraph(
    '<b>Experience:</b> The site demonstrates first-hand experience through its lab articles, which describe building AI systems in the African context. Articles reference specific technical decisions (self-hosted infrastructure, offline-first systems) and geographic specificity (Windhoek, Namibia). However, there are no case studies with measurable outcomes, no client testimonials, and no before/after results that would provide concrete evidence of applied experience.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>Expertise:</b> The content shows subject-matter depth in AI infrastructure and applied AI topics. Articles go beyond surface-level explanations and include technical details about deployment patterns, agent orchestration, and data analysis workflows. The research section adds credibility. However, author bylines are absent from articles, there are no author bio pages, and no external credentials or certifications are displayed anywhere on the site.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>Authoritativeness:</b> The site has no external citations or backlinks from authoritative sources. No team members are listed with industry credentials. The About page identifies Tangison as a Namibian applied AI laboratory but does not reference partnerships, publications, or speaking engagements that would establish authority in the field. The absence of any Google index presence further undermines authority signals.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>Trustworthiness:</b> The site is transparent about its location (Windhoek, Namibia), provides contact information, and has privacy, terms, and cookie policies. HTTPS is enforced, and security headers are comprehensive. However, the lack of team profiles, physical address on the contact page, and business registration details reduces trust signals that Google evaluates for YMYL (Your Money or Your Life) topics.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Content Coverage</b>', h2_style))
story.append(Paragraph(
    'The site covers three main service pillars (Applied AI, AI Infrastructure, AI Consulting) with 16 sub-specialization pages providing depth. Six lab articles address relevant topics for the target audience. The content architecture supports topic clustering with /insights as a hub and individual articles as spokes. However, the homepage body content is thin at approximately 365 words, which is below the 1,500+ word benchmark for informational intent pages. The /products page also has minimal content, listing products without substantial descriptions of their capabilities or benefits.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Content Gaps</b>', h2_style))
story.append(Paragraph(
    'Several high-value content areas are missing entirely. There are no comparison pages (e.g., "Self-Hosted AI vs. Cloud AI for African Businesses"), no alternative pages (e.g., "Alternatives to OpenAI for Private Deployments"), no FAQ pages addressing common customer questions, and no glossary or educational content that would attract informational search traffic. The case studies section (/insights/case-studies) appears to be a placeholder with no actual case studies. No pricing or engagement model information exists anywhere on the site, which is a common gap for B2B service sites but one that prospects frequently search for.',
    body_style
))

story.append(Spacer(1, 8))
story.append(Paragraph('<b>Cannibalization</b>', h2_style))
story.append(Paragraph(
    'No keyword cannibalization issues were detected. Each page targets a distinct topic with unique title tags and meta descriptions. The service sub-specialization pages each address a specific niche (custom-ai-systems, enterprise-deployments, workflow-automation, etc.) without overlapping keyword targets. This is a positive finding that should be maintained as new content is added.',
    body_style
))

# ============================================================
# SECTION 5: LAYER 4 — LINK PROFILE
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Layer 4: Link Profile</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The link profile for tangison.com is essentially non-existent. A Google search for the domain returns zero indexed pages, and no external backlinks were found from authoritative sources. The site appears to be in the earliest stages of its link building journey, with no evidence of any active link acquisition strategy. The Instagram profile for @tangison_studio references studio.tangison.com but does not provide a followed backlink to the main domain.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Internal linking is functional but could be strengthened. The navigation and footer provide baseline internal links, but the hub-and-spoke model for topic clusters is incomplete. Service parent pages do not link to their sub-specializations, and the articles do not consistently link back to relevant service pages. The existing article internalLinks data structure is a good foundation, but the cross-linking density should be increased to at least 5-10 internal links per article page. The studio section, which was recently integrated into tangison.com, needs prominent backlinks from the main navigation and footer to establish its authority within the site hierarchy.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'There are no linkable assets on the site beyond the articles themselves. The research section mentions open-source repositories but does not link to them directly. No free tools, calculators, templates, or downloadable resources exist that would naturally attract backlinks. The resources page (/insights/resources) mentions downloadable guides and frameworks but appears to be a placeholder without actual downloadable content.',
    body_style
))

# ============================================================
# SECTION 6: LAYER 5 — COMPETITIVE POSITION
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Layer 5: Competitive Position</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'Tangison.com operates in the applied AI services space with a geographic focus on Namibia and Africa more broadly. This is a relatively uncrowded niche, which presents both an opportunity and a challenge. The opportunity is that there are few competitors explicitly targeting "applied AI Africa" or "AI laboratory Namibia" as keyword clusters. The challenge is that search demand for these specific terms is likely low, and the site must also compete with global AI consultancies for broader terms like "AI consulting services" and "AI infrastructure solutions".',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'Currently, tangison.com has zero organic visibility. No pages appear in Google search results for any queries, including branded searches for "Tangison". This is entirely explained by the canonical URL misconfiguration pointing to the vercel.app domain. Once this is fixed, the site should begin appearing for branded and long-tail queries within weeks. The site is well-positioned to capture "AI Namibia", "applied AI Africa", and "self-hosted AI infrastructure" keyword clusters if the canonical issue is resolved and structured data is implemented.',
    body_style
))
story.append(Spacer(1, 6))
story.append(Paragraph(
    'The competitive landscape in Namibia for AI services is nascent. Most local competitors are general IT consultancies without specialized AI offerings. International competitors (Accenture, Deloitte AI) dominate broad search terms but lack the geographic specificity and self-hosted infrastructure focus that differentiates Tangison. The content strategy should lean into this differentiation by creating location-specific content (e.g., "AI Regulations in Namibia", "Self-Hosted AI for African Internet Infrastructure") that global competitors will never produce.',
    body_style
))

# ============================================================
# SECTION 7: SUBDOMAIN AUDIT
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Subdomain Audit</b>', h1_style))
story.append(Spacer(1, 6))

sub_data = [
    [Paragraph('<b>Subdomain</b>', header_cell),
     Paragraph('<b>Title</b>', header_cell),
     Paragraph('<b>Canonical</b>', header_cell),
     Paragraph('<b>OG Tags</b>', header_cell),
     Paragraph('<b>H1</b>', header_cell),
     Paragraph('<b>Schema</b>', header_cell)],
    [Paragraph('sme-academy.tangison.com', cell_style),
     Paragraph('SMEfrog Academy', cell_style),
     Paragraph('Missing', cell_center),
     Paragraph('All missing', cell_center),
     Paragraph('Missing', cell_center),
     Paragraph('None', cell_center)],
    [Paragraph('skills.tangison.com', cell_style),
     Paragraph('Tangison SkillsCamp', cell_style),
     Paragraph('Correct', cell_center),
     Paragraph('All present', cell_center),
     Paragraph('Present', cell_center),
     Paragraph('Present', cell_center)],
    [Paragraph('feorm.tangison.com', cell_style),
     Paragraph('Feorm | Book Farm Stays', cell_style),
     Paragraph('Missing', cell_center),
     Paragraph('All missing', cell_center),
     Paragraph('Missing', cell_center),
     Paragraph('None', cell_center)],
    [Paragraph('studio.tangison.com', cell_style),
     Paragraph('Creative Digital Agency', cell_style),
     Paragraph('Correct', cell_center),
     Paragraph('Partial', cell_center),
     Paragraph('Present', cell_center),
     Paragraph('Present', cell_center)],
]
story.append(make_table(sub_data, col_widths=[110, 100, 65, 70, 60, 55]))
story.append(Spacer(1, 6))

story.append(Paragraph(
    '<b>skills.tangison.com</b> is the best-optimized subdomain with correct canonical, full OG tags, proper H1, and JSON-LD structured data. It should serve as the template for fixing the other subdomains.',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>sme-academy.tangison.com</b> and <b>feorm.tangison.com</b> are critically deficient: no canonical tags means Google may index wrong URLs, no OG tags means poor social sharing, and no H1 tags means poor keyword signaling. These need immediate remediation with canonical URLs, meta descriptions, OG tags, heading structure, and structured data (Course schema for SMEfrog Academy, LocalBusiness for Feorm).',
    body_style
))
story.append(Spacer(1, 4))
story.append(Paragraph(
    '<b>studio.tangison.com</b> has the basics in place but uses a generic title ("Creative Digital Agency") without the Tangison brand name, and its OG image points to favicon.webp instead of a proper social sharing image. The recent integration of studio content into tangison.com/studio is a positive move that should continue, with studio.tangison.com eventually redirecting to the main domain.',
    body_style
))

# ============================================================
# SECTION 8: CRITICAL ISSUES & SCORE CARD
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Critical Issues (Fix Immediately)</b>', h1_style))
story.append(Spacer(1, 6))

critical_data = [
    [Paragraph('<b>Issue</b>', header_cell),
     Paragraph('<b>Layer</b>', header_cell),
     Paragraph('<b>Affected</b>', header_cell),
     Paragraph('<b>Severity</b>', header_cell),
     Paragraph('<b>Impact</b>', header_cell)],
]

issues = [
    ('Canonical URLs point to tangison-labs.vercel.app', 'Technical', 'All 39 pages', 'CRITICAL', 'Zero Google indexing; all authority flows to wrong domain'),
    ('Site not indexed by Google', 'Technical', 'Entire site', 'CRITICAL', 'Zero organic visibility; no search traffic possible'),
    ('Zero structured data (JSON-LD)', 'On-Page', 'All 39 pages', 'CRITICAL', 'No rich snippets; Google cannot understand entity relationships'),
    ('Duplicate brand in title tags', 'On-Page', '4 subpages', 'HIGH', '"TANGISON | TANGISON" looks unprofessional and wastes title space'),
    ('No www-to-non-www redirect', 'Technical', 'Homepage', 'HIGH', 'Duplicate content signal; split link equity'),
    ('No trailing slash redirect', 'Technical', 'All pages', 'HIGH', 'Duplicate content risk; same content at two URLs'),
    ('Subdomains missing canonical/OG/H1', 'Technical', 'sme-academy, feorm', 'HIGH', 'Subdomains effectively invisible to search engines'),
    ('/products page has no H1', 'On-Page', '/products', 'HIGH', 'Google cannot determine primary page topic'),
    ('30+ pages share same generic OG image', 'On-Page', '30+ pages', 'MEDIUM', 'Poor social sharing appearance; lost click-through'),
    ('Most pages lack openGraph.url', 'On-Page', '25+ pages', 'MEDIUM', 'OG URL defaults to homepage; social platforms show wrong URL'),
    ('Article heading image has alt=""', 'On-Page', 'Article pages', 'MEDIUM', 'Accessibility and SEO failure for content images'),
    ('Sitemap lastModified all use new Date()', 'Technical', 'All URLs', 'MEDIUM', 'Timestamps change every build, diluting crawl signals'),
    ('Studio subdomain generic title', 'On-Page', 'studio.tangison.com', 'MEDIUM', 'Missing brand name; poor SERP branding'),
    ('Homepage thin content (~365 words)', 'Content', 'Homepage', 'MEDIUM', 'Below 1,500+ word benchmark for informational intent'),
]

for issue_text, layer, affected, severity, impact in issues:
    sev_p, sev_bg = sev_cell(severity, severity)
    row = [
        Paragraph(issue_text, cell_style),
        Paragraph(layer, cell_center),
        Paragraph(affected, cell_center),
        sev_p,
        Paragraph(impact, cell_style),
    ]
    critical_data.append(row)

critical_table = Table(critical_data, colWidths=[140, 55, 70, 55, AVAILABLE_WIDTH - 320], hAlign='CENTER')
ct_style = [
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
]
# Color severity cells
for i, (_, _, _, sev, _) in enumerate(issues, start=1):
    sev_bg_map = {'CRITICAL': CRITICAL_COLOR, 'HIGH': HIGH_COLOR, 'MEDIUM': MEDIUM_COLOR, 'LOW': LOW_COLOR}
    bg = sev_bg_map.get(sev, BG_SURFACE)
    ct_style.append(('BACKGROUND', (3, i), (3, i), bg))
    # Alternating rows for other cells
    row_bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
    for col in [0, 1, 2, 4]:
        ct_style.append(('BACKGROUND', (col, i), (col, i), row_bg))

critical_table.setStyle(TableStyle(ct_style))
story.append(critical_table)

# Veto conditions
story.append(Spacer(1, 12))
story.append(Paragraph('<b>Veto Conditions Check</b>', h2_style))

veto_data = [
    [Paragraph('<b>Condition</b>', header_cell),
     Paragraph('<b>Cap</b>', header_cell),
     Paragraph('<b>Status</b>', header_cell),
     Paragraph('<b>Triggered?</b>', header_cell)],
    [Paragraph('robots.txt blocks all of Googlebot', cell_style),
     Paragraph('Overall 1/10', cell_center),
     Paragraph('Not blocked', cell_center),
     Paragraph('No', cell_center)],
    [Paragraph('> 20% of important pages have accidental noindex', cell_style),
     Paragraph('Overall 3/10', cell_center),
     Paragraph('No noindex tags found', cell_center),
     Paragraph('No', cell_center)],
    [Paragraph('All three Core Web Vitals are Poor', cell_style),
     Paragraph('Technical 3/10', cell_center),
     Paragraph('Not assessed (SSG + Vercel = likely Good)', cell_center),
     Paragraph('Unlikely', cell_center)],
    [Paragraph('Zero external backlinks (entire domain)', cell_style),
     Paragraph('Link Profile 2/10', cell_center),
     Paragraph('Confirmed: zero backlinks', cell_center),
     Paragraph('<b>YES - Cap applied</b>', cell_center)],
    [Paragraph('Site serves HTTP without redirect to HTTPS', cell_style),
     Paragraph('Technical 4/10', cell_center),
     Paragraph('HTTPS enforced correctly', cell_center),
     Paragraph('No', cell_center)],
]
story.append(make_table(veto_data, col_widths=[180, 75, 140, AVAILABLE_WIDTH - 395]))

# ============================================================
# SECTION 9: 90-DAY ACTION PLAN
# ============================================================
story.append(Spacer(1, 18))
story.append(Paragraph('<b>90-Day Action Plan</b>', h1_style))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>Month 1: Fix the Foundation</b>', h2_style))
story.append(Paragraph(
    'The first month is entirely dedicated to resolving the critical technical issues that currently prevent the site from appearing in Google search results. Without these fixes, no other SEO work will produce measurable results. The canonical URL fix is the single highest-impact action in this entire audit, as it will unlock Google indexing for the entire site.',
    body_style
))
story.append(Spacer(1, 4))

m1_data = [
    [Paragraph('<b>Action</b>', header_cell),
     Paragraph('<b>Priority</b>', header_cell),
     Paragraph('<b>Effort</b>', header_cell),
     Paragraph('<b>Expected Impact</b>', header_cell)],
    [Paragraph('Fix metadataBase in root layout to use https://tangison.com (not vercel.app)', cell_style),
     Paragraph('P0', cell_center), Paragraph('Low', cell_center),
     Paragraph('Unlocks Google indexing for all 39 pages', cell_style)],
    [Paragraph('Add 301 redirect: www.tangison.com to tangison.com', cell_style),
     Paragraph('P0', cell_center), Paragraph('Low', cell_center),
     Paragraph('Eliminates duplicate content signal', cell_style)],
    [Paragraph('Add trailing slash redirect (consistent URL format)', cell_style),
     Paragraph('P1', cell_center), Paragraph('Low', cell_center),
     Paragraph('Eliminates duplicate content risk', cell_style)],
    [Paragraph('Fix duplicate brand in title tags (4 pages)', cell_style),
     Paragraph('P1', cell_center), Paragraph('Low', cell_center),
     Paragraph('Professional SERP appearance; better title space usage', cell_style)],
    [Paragraph('Add /products H1 heading', cell_style),
     Paragraph('P1', cell_center), Paragraph('Low', cell_center),
     Paragraph('Proper keyword signaling for products page', cell_style)],
    [Paragraph('Fix article heading image alt="" to use article title', cell_style),
     Paragraph('P1', cell_center), Paragraph('Low', cell_center),
     Paragraph('Accessibility + SEO for content images', cell_style)],
    [Paragraph('Add robots.txt Disallow for /api/ and /_next/', cell_style),
     Paragraph('P2', cell_center), Paragraph('Low', cell_center),
     Paragraph('Prevents crawl budget waste on technical paths', cell_style)],
    [Paragraph('Fix sitemap lastModified to use actual content dates', cell_style),
     Paragraph('P2', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Accurate crawl signals for search engines', cell_style)],
    [Paragraph('Add /studio to sitemap', cell_style),
     Paragraph('P2', cell_center), Paragraph('Low', cell_center),
     Paragraph('Studio page discoverable via sitemap', cell_style)],
    [Paragraph('Submit sitemap to Google Search Console', cell_style),
     Paragraph('P0', cell_center), Paragraph('Low', cell_center),
     Paragraph('Accelerates Google discovery and indexing', cell_style)],
]
story.append(make_table(m1_data, col_widths=[200, 50, 55, AVAILABLE_WIDTH - 305]))

story.append(Spacer(1, 12))
story.append(Paragraph('<b>Month 2: Strengthen Content and Structured Data</b>', h2_style))
story.append(Paragraph(
    'With the technical foundation repaired, Month 2 focuses on adding structured data (which provides the highest content-ROI for SEO), expanding thin content, and fixing the subdomain configurations. Structured data implementation should follow a prioritized order: Organization and WebSite schema first (homepage), then Article schema (blog posts), then Service and Product schema (service and product pages), and finally BreadcrumbList schema (all pages).',
    body_style
))
story.append(Spacer(1, 4))

m2_data = [
    [Paragraph('<b>Action</b>', header_cell),
     Paragraph('<b>Priority</b>', header_cell),
     Paragraph('<b>Effort</b>', header_cell),
     Paragraph('<b>Expected Impact</b>', header_cell)],
    [Paragraph('Implement JSON-LD: Organization + WebSite schema on homepage', cell_style),
     Paragraph('P0', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Rich snippets; knowledge panel eligibility', cell_style)],
    [Paragraph('Implement JSON-LD: Article schema on all article pages', cell_style),
     Paragraph('P0', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Article rich snippets with author/date in SERP', cell_style)],
    [Paragraph('Implement JSON-LD: Service + Product schema', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Service/product rich snippets in SERP', cell_style)],
    [Paragraph('Implement JSON-LD: BreadcrumbList on all pages', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Breadcrumb trail in SERP; improved site understanding', cell_style)],
    [Paragraph('Expand homepage content to 1,000+ words', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Better topical authority signal for primary domain', cell_style)],
    [Paragraph('Fix sme-academy.tangison.com: add canonical, OG, H1, Course schema', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Subdomain becomes indexable and shareable', cell_style)],
    [Paragraph('Fix feorm.tangison.com: add canonical, OG, H1, LocalBusiness schema', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Subdomain becomes indexable and shareable', cell_style)],
    [Paragraph('Fix studio.tangison.com: branded title, proper OG image', cell_style),
     Paragraph('P2', cell_center), Paragraph('Low', cell_center),
     Paragraph('Brand consistency in SERP and social sharing', cell_style)],
    [Paragraph('Add page-specific OG images for top 10 pages', cell_style),
     Paragraph('P2', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Improved social sharing click-through rates', cell_style)],
    [Paragraph('Add page-specific openGraph.url to all pages', cell_style),
     Paragraph('P2', cell_center), Paragraph('Low', cell_center),
     Paragraph('Correct URL display on social platforms', cell_style)],
]
story.append(make_table(m2_data, col_widths=[200, 50, 55, AVAILABLE_WIDTH - 305]))

story.append(Spacer(1, 12))
story.append(Paragraph('<b>Month 3: Build Authority and Competitive Position</b>', h2_style))
story.append(Paragraph(
    'With the technical foundation solid and content structured for search engines, Month 3 shifts to building external authority and capturing competitive keyword positions. The focus should be on creating linkable assets, pursuing strategic backlinks, and developing content that fills the identified gaps in the topic cluster. The geographic specificity of Namibia and Africa is a significant competitive advantage that should be leveraged in all content and link building efforts.',
    body_style
))
story.append(Spacer(1, 4))

m3_data = [
    [Paragraph('<b>Action</b>', header_cell),
     Paragraph('<b>Priority</b>', header_cell),
     Paragraph('<b>Effort</b>', header_cell),
     Paragraph('<b>Expected Impact</b>', header_cell)],
    [Paragraph('Create 3 linkable assets (AI Readiness Calculator, Namibia AI Report, Deployment Guide)', cell_style),
     Paragraph('P1', cell_center), Paragraph('High', cell_center),
     Paragraph('Attracts natural backlinks; establishes authority', cell_style)],
    [Paragraph('Write 4 location-specific articles targeting "AI Namibia" keyword cluster', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Captures geographic long-tail searches competitors ignore', cell_style)],
    [Paragraph('Add comparison/alternative pages (self-hosted vs. cloud AI)', cell_style),
     Paragraph('P1', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Captures commercial investigation intent', cell_style)],
    [Paragraph('Populate case studies section with 3 real project writeups', cell_style),
     Paragraph('P1', cell_center), Paragraph('High', cell_center),
     Paragraph('E-E-A-T signals; conversion + authority', cell_style)],
    [Paragraph('Submit to Namibian and African tech directories', cell_style),
     Paragraph('P2', cell_center), Paragraph('Low', cell_center),
     Paragraph('Local citation building; geographic relevance signals', cell_style)],
    [Paragraph('Increase internal link density: 5-10 links per article, cross-link services', cell_style),
     Paragraph('P2', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Distributes authority; improves crawl efficiency', cell_style)],
    [Paragraph('Add author bylines and bio pages to all articles', cell_style),
     Paragraph('P2', cell_center), Paragraph('Medium', cell_center),
     Paragraph('E-E-A-T improvement; article rich snippet eligibility', cell_style)],
    [Paragraph('Create FAQ page targeting common AI deployment questions', cell_style),
     Paragraph('P2', cell_center), Paragraph('Medium', cell_center),
     Paragraph('FAQ rich snippets; captures question-based queries', cell_style)],
    [Paragraph('Add article:published_time and article:author OG metadata', cell_style),
     Paragraph('P3', cell_center), Paragraph('Low', cell_center),
     Paragraph('Improved article metadata for social platforms', cell_style)],
    [Paragraph('Dynamically generate sitemap from articles data layer', cell_style),
     Paragraph('P3', cell_center), Paragraph('Medium', cell_center),
     Paragraph('Auto-maintained sitemap; no manual updates needed', cell_style)],
]
story.append(make_table(m3_data, col_widths=[200, 50, 55, AVAILABLE_WIDTH - 305]))

# ─── Build Document ──────────────────────────────────────────
output_path = '/home/z/my-project/download/seo-audit-tangison-body.pdf'

doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='SEO Audit: tangison.com',
    author='Z.ai',
    creator='Z.ai',
    subject='Comprehensive SEO Audit Report for tangison.com'
)

doc.build(story)
print(f'Body PDF generated: {output_path}')
